//
// Autogenerated by Thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./elasticsearch_types');
//HELPER FUNCTIONS AND STRUCTURES

var Rest_execute_args = function(args){
  this.request = null
if( args != null ){  if (null != args.request)
  this.request = args.request
}}
Rest_execute_args.prototype = {}
Rest_execute_args.prototype.read = function(input){ 
  var ret = input.readStructBegin()
  while (1) 
  {
    var ret = input.readFieldBegin()
    var fname = ret.fname
    var ftype = ret.ftype
    var fid   = ret.fid
    if (ftype == Thrift.Type.STOP) 
      break
    switch(fid)
    {
      case 1:      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.RestRequest()
        this.request.read(input)
      } else {
        input.skip(ftype)
      }
      break
      default:
        input.skip(ftype)
    }
    input.readFieldEnd()
  }
  input.readStructEnd()
  return
}

Rest_execute_args.prototype.write = function(output){ 
  output.writeStructBegin('Rest_execute_args')
  if (null != this.request) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1)
    this.request.write(output)
    output.writeFieldEnd()
  }
  output.writeFieldStop()
  output.writeStructEnd()
  return
}

var Rest_execute_result = function(args){
  this.success = null
if( args != null ){  if (null != args.success)
  this.success = args.success
}}
Rest_execute_result.prototype = {}
Rest_execute_result.prototype.read = function(input){ 
  var ret = input.readStructBegin()
  while (1) 
  {
    var ret = input.readFieldBegin()
    var fname = ret.fname
    var ftype = ret.ftype
    var fid   = ret.fid
    if (ftype == Thrift.Type.STOP) 
      break
    switch(fid)
    {
      case 0:      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RestResponse()
        this.success.read(input)
      } else {
        input.skip(ftype)
      }
      break
      default:
        input.skip(ftype)
    }
    input.readFieldEnd()
  }
  input.readStructEnd()
  return
}

Rest_execute_result.prototype.write = function(output){ 
  output.writeStructBegin('Rest_execute_result')
  if (null != this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0)
    this.success.write(output)
    output.writeFieldEnd()
  }
  output.writeFieldStop()
  output.writeStructEnd()
  return
}

var RestClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {}
}
RestClient.prototype = {}
RestClient.prototype.execute = function(request,callback){
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
    this.send_execute(request)
}

RestClient.prototype.send_execute = function(request){
  var output = new this.pClass(this.output);
  output.writeMessageBegin('execute', Thrift.MessageType.CALL, this.seqid)
  var args = new Rest_execute_args()
  args.request = request
  args.write(output)
  output.writeMessageEnd()
  return this.output.flush()
}

RestClient.prototype.recv_execute = function(input,mtype,rseqid){
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException()
    x.read(input)
    input.readMessageEnd()
    return callback(x);
  }
  var result = new Rest_execute_result()
  result.read(input)
  input.readMessageEnd()

  if (null != result.success ) {
    return callback(null, result.success);
  }
  return callback("execute failed: unknown result");
}
var RestProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
RestProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin()
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output)
  } else {
    input.skip(Thrift.Type.STRUCT)
    input.readMessageEnd()
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname)
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid)
    x.write(output)
    output.writeMessageEnd()
    output.flush()
  }
}

RestProcessor.prototype.process_execute = function(seqid, input, output) {
  var args = new Rest_execute_args()
  args.read(input)
  input.readMessageEnd()
  var result = new Rest_execute_result()
  this._handler.execute(args.request, function(success) {
    result.success = success
    output.writeMessageBegin("execute", Thrift.MessageType.REPLY, seqid)
    result.write(output)
    output.writeMessageEnd()
    output.flush()
  })
}

